### ISSUE TITLE
Stuck on the result

### ISSUE THREAD

**Issue by expiteRz** [CLF78/HideNSeek#4]
The round is over then, sometimes the game doesn't show the results and the players can't continue the game.
I confirmed the issue in v1.8 NTSC-J.

**Comment by CLF78** [comment]
Sorry for taking so long replying to the issue. Anyway, sometimes results are delayed from laggy players or disconnections during that phase of the game. Are you sure it didn't happen because of that?

**Comment by expiteRz** [comment]
sorry for late reply too.
i played the game with my friend, but either are using different platform; mine is a real wii, and my friend's is dolphin.
so it can be get desync each other, maybe?

**Comment by expiteRz** [comment]
since the latest version, the players could not reach to the result screen or the voting screen. is it because of wiimmfi, and you failed to fix the issue, right?

**Comment by CLF78** [comment]
It is because of Wiimmfi's bullshit, but it has been already fixed. It simply hasn't been shipped yet due to another thing i would like to finish first. Closing the issue for the time being.
