### ISSUE TITLE
Change flag strings and prevent using Battle Arenas

### ISSUE THREAD

**Issue by mvort** [CLF78/HideNSeek#9]
@CLF78 

Hi, 

would you mind helping me out? 

I'm trying to find where flag strings are stored (e.g. "NORMAL", "HALF", "EXTREME") and how to prevent picking battle arenas when random selection is used.

**Comment by CLF78** [comment]
https://github.com/CLF78/HideNSeek/tree/main/files/UIPatches/Global/message
